# BattlePass
# Made by GC, Hyfe, Zak

# Version: 4.6.11
# Release date: 26/08/2024

# Do not change this version unless instructed to.
config-version: 1

# Fill out this information if you are using a database connection (MySQL).
storage-options:
  # This will delay the loading of user data for half a second to make sure the server the user came from has saved their data.
  # Use this if you are using ANY database that is not directly file based. JSON does not need this.
  bungee-fix: false

  # How many seconds that are between each save, therefore avoiding data loss.
  auto-save-interval: 180

  # How the plugin stores data. Either JSON (flat file) or MySQL (database).
  storage-method: JSON

  # The address used for connection.
  # If you have a custom MySQL port use formatting 'localhost:3306'
  address: localhost

  # Text that is prefixed before the table names
  prefix: battlePass-

  # The name of the database that BattlePass will use.
  # You must create this as it will not be automatically generated.
  database: battlePass

  # The information used to log in.
  username: battlepassuser
  password: 'verySafe'

  # These are additional settings for MySQL connections.
  # You should only change these settings if you know what you're doing.
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000
    connection-timeout: 5000

  # These properties will most likely not need changing unless you encounter issues.
  connection-properties:

    # You may want to disable this if you are getting SSL errors,
    # However, we always recommend you use SSL where possible.
    useSSL: true

# This is provided in seconds, you can not use decimals
join-message-delay: 5

enable-ban-permission: false # Enables the battlepass.block permission which blocks users from using the battlepass.

# Set as [] at the end to disable either.
whitelisted-worlds: [] # Use the same format as blacklisted worlds if you wish to use whitelisted worlds. You can use both at the same time.
blacklisted-worlds: # World names where quests cannot be progressed.
  - 'world_with_no_quests'
  - 'another_world'

daily-quests-enabled: true # If this value is set to false it will disable calculation of daily quests
# Get daily quests from bungee server
# To make it work, one server in bungee proxy, should be set as 'false' and other servers should be set as 'true'
daily-quests-use-bungee: false

permanent-daily-quest-ids: [] # ['1', '3', '5']

# Actions that are run whenever any player completes any quest, for that player.
# This is empty by default, set it like this if you want actions:
#
# quest-completed-actions:
#   - '[message]{Well you did something}'
quest-completed-actions:
  - '[title]{&eQuest completed!}'
  - '[subtitle]{&e%quest_name%&f is now completed}'

current-season:
  time-zone: 'Europe/Oslo' # The timezone for week releases to be based off.
  start-date: '06/06/2020' # This is what all of the week releases are based off. Format: dd/mm/yyyy
  start-time: '20:00' # The time of day week releases are based off.
  notification-method: 'action bar & chat' # How notifications will be sent to players. Options: action bar, chat, action bar & chat or none.
  auto-receive-rewards: false # If this value is set to false players will need to click a reward in the gui to claim it
  daily-quest-reset-time: '12:00'
  daily-quest-amount: 9 # Amount of daily quests that will be available at one time
  quest-glow-on-completion: true # If quests will have an enchanted glow if they are completed.
  completionCustomModelData: 0
  completionMaterial: "" # Use "" to disable
  notify-at-percentages: [10, 25, 50, 75, 100]
  # Auto generate each week from `quests/week-pool.yml`
  # Plugin will generate quests after starting new season
  # **Plugin will remove old weeks!**
  #
  # Starting new season when this option is enabled can cause small lags, so don't use it when server isn't empty
  auto-generate-weekly-quests:
    enable: false
    allow-duplicated: true
    weeks: 4
    free-quests-per-week: 4
    premium-quests-per-week: 4
  unlocks:
    require-previous-completion: false # Whether the user must complete all missions in the previous week to start the next week.
    lock-previous-weeks: false # Whether previous weeks will be locked when a new week is released.

season-finished:
  stop-daily-quests: false # Whether once the season is finished, daily quests will stop being rolled / progress not counted.
  stop-other-quests: false # If set to true, anything other than daily quests will not be progressable. Combine with the option above to block all quests.

#disabled-plugin-hooks: # This will disable the loading for any quests from the specified plugin. You can use this if you use an outdated version of them and it's causing errors to stop them.
#  - 'AutoSell'
#  - 'PlotSquared'

enable-play-time: false # Switch this to true if you're going to use a playtime quest.

reward-excess-points: # If set to vault, Vault & an economy plugin is required. If set to internal, no other plugins are required.
  method: none # Set this to none, vault or internal. If it's internal, the value will be stored within BattlePass and you must use commands to add/remove and placeholders to get.
  currency-per-point: # The amount of currency given per every excess point.
    free: 50
    premium: 100

fixes:
  use-improved-tier-points: true # Previously if you set 300 points for tier 10, that would mean 300 points to tier 11. This makes it so it's logical and it's 300 points to reach tier 10.

# Enable this setting to add brewing protection. It will add NBT Tag to potion after brewing to make sure that players won't use same potion to finish quest.
# Disable it only if you don't use brew quest
brewing-protection: true

# Enable this setting to add break protection. If enabled, block-break quests won't progress if player destroys block which has been placed by another player.
break-protection: true

# Enable this setting if block-break quest doesn't work with skyblock cobble/ore generators.
# It will bypass cache of placed/broken blocks as some skyblock generators seem to not work with block breaking
force-skyblock-generator-support: false

boss-bar:
  enabled: false
  persistent: false
  hide-after: 5 # How long to show the boss bar after a quest is progressed (IN SECONDS). If persistent, this setting does not apply
  use-notify-percentages: true # If true, the boss bar will only be shown when one of the progression thresholds is reached
  disabled-quest-types:
    - 'fly'
    - 'glide'
    - 'sneak'
    - 'walk'
    - 'sprint'
    - 'move'
  # 1.9+ settings ONLY
  color: PINK # must be a color from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html and in all caps
  style: SOLID # must be a style from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html and in all caps

# Should weekly quests' displayed item's amount represent the week? E.g. week 3's quest items will have an amount of 3
weekly-quest-item-amounts: true
battle-pass-aliases: []

# SUM - If player has multiple boosters, plugin will sum them
# Example:
# - Server booster +10%
# - Player booster +7%
# - Player booster +5%
# Final booster: 10 + 7 + 5 = 22%
#
# SUM_DIFFERENT - If player has multiple boosters, highest server booster will be added to the highest player booster
# Example:
# - Server booster +10%
# - Player booster +7%
# - Player booster +5%
# Final booster: 10 + 7 = 17%
#
# HIGHEST - If player has multiple boosters, plugin will use the highest booster
# Example:
# - Server booster +10%
# - Player booster +7%
# - Player booster +5%
# Final booster: 10%
#
boosters-strategy: SUM_DIFFERENT
# Show ID of week/quest (permission: battlepass.debug.id)
menu-show-id: true
menu-auto-add-booster-lore: true

# When feature is enabled, players need to select quest to be able to complete it
# Player can only select limited number of quests
# Limit is specified by default value and using permission
# Player can also cancel quest, but it will cause loosing progress of that quest
quest-select:
  enable: false
  default-limit: 1
  limit-permission: "battlepass.quest.limit.<num>"
  max-limit: 10
  # Automatically add selection status to end of quest's lore
  # When disabled, you need to manually add %select_status% placeholder to lore of each quest
  auto-add-status: true
  # Format of selected quest's name in quest-overview menu
  # Used in placeholder %selected_quests%
  selected-quest-format: "&7» &6%name%"

leaderboards:
  # Create leaderboard cache and update it every X minutes.
  # Recommended for servers with large amount of players - if disabled on these server, plugin can crash when opening leaderboard
  # Disable only on low memory servers
  use-cache: true
  # Refresh leaderboard cache every X minutes
  # Use placeholder %battlepass_top_time% to get time to refresh
  cache-refresh-minutes: 10
  # Name of player if plugin couldn't find that player in server's cache
  not-found-name: "Error"
