name: "BattlePass"
version: "3.13"
main: io.github.battlepass.BattlePlugin
api-version: 1.13
soft-depend:
  - AdvancedEnchantments
  - ASkyBlock
  - AuctionHouse
  - Bedwars1058
  - BuildBattle
  - ChatReaction
  - ChestShop
  - Clans
  - Citizens
  - ClueScrolls
  - CrateReloaded
  - CratesPlus
  - CrazyCrates
  - CrazyEnvoy
  - DiscordMinecraft
  - Factions
  - Jobs
  - SkillAPI
  - KoTH
  - Lands
  - PlaceholderAPI
  - MoneyHunters
  - PlotSquared
  - ProCosmetics
  - Shopkeepers
  - StrikePractice
  - SuperiorSkyblock2
  - TheLab
  - TokenEnchant
  - USkyBlock
  - Votifier
  - UltraSkyWars
  - LuxuryQuests
  - LobbyPresents

commands:
  battlepass:
    description: Well. The main command I guess?
  battlepassadmin:
    aliases: [bpa, battlepassa, bpadmin]
    permission: battlepass.admin
  battlepassdebug:
    aliases: [bpd, bpdebug]
    permission: battlepass.admin

permissions:
  battlepass.admin:
    description: none