name: Feature Request
description: Request a feature with BattlePass
labels: ["Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a feature request. Before you fill this out, please read the following:
        1. Ensure this is not yet achieveable with current featureset.
        2. Be sure that this feature doesn't only benefit you but other issues, we will not accept requests which are specific or do not benefit others.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Describe the feature request in as much detail as you can.
    validations:
      required: true
